#!/bin/bash

BLUE='\033[1;34m'
BOLD='\033[1m'
RESET='\033[0m'

print_info () {
    printf "${BLUE}Info: ${RESET}${1}\n"
}

M2_HOME="${HOME}/.m2"
mkdir -p "${M2_HOME}"

M2_LOCAL_REPO="${PWD}/.m2/repository"

mkdir -p "${M2_LOCAL_REPO}"

cat > ${M2_HOME}/settings.xml <<EOF
<settings   xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                http://maven.apache.org/xsd/settings-1.0.0.xsd">

    <localRepository>${M2_LOCAL_REPO}</localRepository>

    <mirrors>
        <mirror>
            <id>virtual-release</id>
            <name>Artifactory</name>
            <url>${ARTIFACTORY_URL}/virtual-release</url>
            <mirrorOf>central</mirrorOf>
        </mirror>
    </mirrors>

</settings>
EOF

print_info "Configured local mvn repository: [${BOLD}${M2_LOCAL_REPO}${RESET}]"
